spring:
  aws:
    s3:
      bucket-name: blogsystemfor
      region: eu-north-1
      access-key: AKIA4AQ3UFIWDIR4K4U3
      secret-key: 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

  datasource:
    url: jdbc:postgresql://db:5432/blog
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
openapi:
  version: "3.0.0"
  info:
    title: "Your API"
    description: "API documentation for the Blog System"
    version: "1.0.0"

logging:
  level:
    tmrv.dev.blogsystem.controller.PostController: DEBUG
    org.springframework.security: DEBUG
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

