spring:
  aws:
    s3:
      bucket-name: blogsystemfor
      region: eu-north-1
      access-key: 1
      secret-key: 2

  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    tmrv.dev.blogsystem.controller.PostController: DEBUG
    org.springframework.security: DEBUG
